export interface HospitalListType {
  address: string | null;
  breaktime: string | null;
  createAt: null;
  detailDrNumber: string | null;
  distance: number | null;
  doNm: string | null;
  dongNm: string | null;
  drNumber: string | null;
  emergency: string | null;
  fri: string | null;
  hospitalNm: string;
  id: number | null;
  kmDistance: string | null;
  lat: number;
  lng: number;
  medicalDepartment: string | null;
  medicalInstitutionType: string | null;
  mon: string | null;
  nightCare: null;
  nightCareDay: null;
  numberOfBeds: null;
  phoneNumber: string | null;
  roadNm: string | null;
  sat: string | null;
  sigunguNm: string | null;
  sun: string | null;
  thu: string | null;
  tue: string | null;
  updateAt: string | null;
  webpage: string | null;
  wed: string | null;
}
